stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\train.csv
    deps:
    - .\src\data\make_dataset.py 
    - .\data\raw\train.csv
    params:
    - make_dataset.test_size
    - make_dataset.seed
  build_features:
    cmd: python .\src\features\build_features.py .\data\interim\train.csv .\data\interim\test.csv
    deps:
    - .\src\features\build_features.py