stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\train.csv
    deps:
    - .\src\data\make_dataset.py 
    - .\data\raw\train.csv
    params:
    - make_dataset.test_size
    - make_dataset.seed