make_dataset:
  test_size: 0.3
  seed: 42
train_model:
  alpha: [1.0,0.5,1.5,0.8]
  max_iter: [1000,800,900,1500]
  l1_ratio: [0.5, 0.8,0.2]
  criterion: ['squared_error', 'friedman_mse', 'absolute_error', 'poisson']
  splitter: ['best', 'random']
  max_features: [0.5, 0.25]
  n_estimators: [8,64,128,256,512]
  learning_rate: [.1,.01,0.5,.001]
  loss: ['linear','square','exponential']
  loss_g: ['squared_error', 'absolute_error', 'huber', 'quantile']
  subsample: [0.6,0.75,0.8,0.9]
  criterion_g: ['squared_error', 'friedman_mse']
  base_estimator: ["LinearRegression()", "Ridge()", "Lasso()", "DecisionTreeRegressor()"]
  bagging_n_estimators: [500, 100, 250]
  max_samples: [0.25, 0.50]